### ISSUE TITLE
Satiator Menu v66 is getting black screen on FW 159

### ISSUE THREAD

**Issue by ferraca** [satiator/compatibility#26]
Hi! I've just updated to the FW 159. But since that, the Satatiator Rings 5.5 menu is taking longer to be accessed than it used to take in FW 158. Also, when I ask Rings to exit to Satiator Menu (v66), I get black screen. None of this were happening on FW 158. My setup is Saturn model 1, Bios v1.00a NTSC. SD card is Kingston 128gb Class 10. Any idea? Thank you!!!

EDITED: I tested it removing "autoboot.iso" from the SD Card and the Satiator Menu v66 worked just fine. Then I put back the "autoboot.iso" there, and the same issue happened. So, not sure if it a problem with Rings or last firmware. Thank you again!

**Comment by abrasive** [comment]
Hiya! This issue is specific to Rings so I'm afraid I can't really help with it. Some of the early release candidates (particularly rc159-1) did dramatically slow down filesystem access, which did affect Rings, but this was resolved by rc159-3 and in the final fw159 release, according to measurements.

You're using the released firmware yeah, not one of the release candidates?

**Comment by ferraca** [comment]
Hi! Professor Abrasive!! Thanks for your response. I am using the firmware provided in your website: "satiatorfw159.zip" / https://wiki.satiator.net/start#software_updates
